spring.application.name=api-gateway

services.customer.url=http://customer-service:8081
services.restaurant.url=http://restaurant-service:8082
services.order.url=http://order-service:8083
services.delivery.url=http://delivery-service:8084


# Server port
server.port=8080

# JWT configuration
app.jwt.secret=${JWT_SECRET:mysecretkey}

# Eureka Client configuration
eureka.client.service-url.defaultZone=http://registry-service:8761/eureka/

# Spring Cloud Gateway routes
spring.cloud.gateway.mvc.routes[0].filters[0]=JwtAuthenticationFilter

spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=lb://CUSTOMER-SERVICE
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.mvc.routes[1].id=customer-service
spring.cloud.gateway.mvc.routes[1].uri=lb://CUSTOMER-SERVICE
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/customers/**

spring.cloud.gateway.mvc.routes[2].id=restaurant-service
spring.cloud.gateway.mvc.routes[2].uri=lb://RESTAURANT-SERVICE
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/restaurants/**

spring.cloud.gateway.mvc.routes[3].id=order-service
spring.cloud.gateway.mvc.routes[3].uri=lb://ORDER-SERVICE
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/orders/**

spring.cloud.gateway.mvc.routes[4].id=delivery-service
spring.cloud.gateway.mvc.routes[4].uri=lb://DELIVERY-SERVICE
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/deliveries/**