spring.application.name=order-service

# External service URLs
services.customer.url=http://customer-service:8081
services.restaurant.url=http://restaurant-service:8082

# Eureka Client configuration
eureka.client.service-url.defaultZone=http://registry-service:8761/eureka/



# Server port
server.port=8083

# Database configuration
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.url=jdbc:postgresql://order-db:5432/order_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


# RabbitMQ configuration
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


# Feign client configuration
feign.circuitbreaker.enabled=true

# Resilience4j Circuit Breaker configuration for CUSTOMER-SERVICE
resilience4j.circuitbreaker.instances.CUSTOMER-SERVICE.sliding-window-size=10
resilience4j.circuitbreaker.instances.CUSTOMER-SERVICE.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.CUSTOMER-SERVICE.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.CUSTOMER-SERVICE.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.CUSTOMER-SERVICE.permitted-number-of-calls-in-half-open-state=3

# Actuator configuration
management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true